title: Clair Berlin
copyright: 2020 Clair Berlin
url: https://clair-berlin.de
# baseurl: /clair
email: kontakt@clair-berlin.de
description: Clair Berlin - Initiative zur Messung der Luftqualität in öffentlich zugänglichen Räumen
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
gems:
  - jekyll-liquify
exclude:
  - README.md
  - LICENSE.txt
